// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvqllbzyqhuibnppntay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cWxsYnp5cWh1aWJucHBudGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjgyNDgsImV4cCI6MjA2NDk0NDI0OH0.Oz6w7w7QqfkIQxeDPqc2y3G4qyWBN676i9c0GV4xhS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);